### ISSUE TITLE
Question on setting parameters

### ISSUE THREAD

**Issue by jeffreylovitz** [cleishm/libcypher-parser#24]
What is the recommended way to set parameters in libcypher-parser?

`":param x => [1,2];"` results in:
```
@0   0..17  command   name=@1, args=[@2, @3, @4]
@1   1..6   > string  "param"
@2   7..8   > string  "x"
@3   9..11  > string  "=>"
@4  12..17  > string  "[1,2]"
```

Looking at the `client-arg-string` definition in the source, it seems that arguments are always interpreted as simple strings. Would it be difficult to parse parameter values as atoms instead, or does that pose issues I haven't considered?

**Comment by cleishm** [comment]
I don't imagine parsing the `:param` comamnd presents any major challenges, especially as, `:param x => ...` isn't part of the Cypher grammar.

The challenge is how that would interplay with tools that use the parameter parsing, like https://neo4j-client.net/.

**Comment by cleishm** [comment]
Actually, one big issue would be determining what tokens are expressions and what are not. The command parsing just recognizes `:<symbolic_name>` followed by arguments. Which of those arguments are to be considered Cypher expressions is entirely dependent on what the command represents, which is something the parser doesn't know (because there is no standard).
